source 'http://rubygems.org'

gem 'activesupport', '5.2.2'
gem 'bcrypt'
gem 'dotenv'
gem 'faker'
gem 'gem-path'
gem 'httparty'
gem 'minitest'
gem 'newrelic_rpm'
gem 'nt_models', '0.1.3'
gem 'pg'
gem 'rack'
gem 'rack-test'
gem 'rails_helper'
gem 'rake'
gem 'rb-readline'
gem 'sinatra'
gem 'sinatra-flash'
gem 'simplecov'
gem 'thin'

group :development do
  gem 'pry-byebug'
end
