development:
  adapter: postgresql
  encoding: unicode
  database: ntwitter_dev
  pool: 2
  migrations_paths: <%= "#{`gem path nt_models`.gsub("\n", '')}/db/migrate" %>

test:
  adapter: postgresql
  encoding: unicode
  database: ntwitter_test
  pool: 2
  migrations_paths: <%= "#{`gem path nt_models`.gsub("\n", '')}/db/migrate" %>

production:
  adapter: postgresql
  encoding: unicode
  database: ntwitter_prod
  pool: 2
  migrations_paths: <%= "#{`gem path nt_models`.gsub("\n", '')}/db/migrate" %>
  username: your_username
  password: your_password
